
# Index error in python function for pandas

I've build a function that eliminates rows over a selected dataframe. I simply select the DF, the main column (validation) and a second column that contains an oposite movement in SAP. When I run it, it showme an index error. I have no idea how to solve this error, I thought of reseting the index but it didn't work. Somebody has any comments?  Thank you for your support!
def Erase_del_movements(df,columna,columna2):
    
    """ This functions seach SAP's movements targeted as 102 to eliminate it and its 101"""
    
    a=df[columna].shape
    b=a[0]
    
    for x in np.arange(1,b): #inicio el ciclo de evaluaci√≥n
        h=0
        while  x<= b:
            if df[columna][x]==102:
                for y in np.arange(x-5,x+5,1):
                        if df[columna2][x]==df[columna2][y]:
                            df.drop(axis=0,index=[y], inplace=True)
                            df.drop(axis=0,index=[x], inplace=True)
                            df.reset_index()    
                            break
            break              
    
    return df


ERROR:
  6642 if mask.any():
   6643     if errors != "ignore":
-> 6644         raise KeyError(f"{list(labels[mask])} not found in axis")
   6645     indexer = indexer[~mask]
   6646 return self.delete(indexer)

KeyError: '[403] not found in axis'



        