
# python breakpoint() default entry point is one level down than expected

I am having a strange problem with breakpoint() that I have never encountered before. It is stepping into the program a level down than it usually does. I can recover the previous default behaviour by pressing 'u'.
I am using python 3.9, conda environment in pycharm 2021.3.1
For example:
def hello():
    return "hello"

x = 1
breakpoint()
hello()

Will start the debugger from within the function hello(). If I type 'x' I will not be able to see the variable, as am in the function workspace. Pressing 'u' allows me to get back to where breakpoint(), when working as expected, used to break into.
I must have changed the default somewhere but I cannot for the life of me find where, I seem to have no PYTHONBREAKPOINT environment variable set...

        