
# Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set \\ RuntimeError: Working outside of application context [duplicate]







This question already has answers here:
                        
                    



Flask-SQLAlchemy db.create_all() raises RuntimeError working outside of application context

                                (2 answers)
                            


Flask SQLAlchemy db.create_all() not creating database

                                (1 answer)
                            

Closed 8 hours ago.



finally I solved this problem with venv and now I'm stuck with this problem.

from app import db
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
db.create_all()
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\flask_sqlalchemy\extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\flask_sqlalchemy\extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\flask_sqlalchemy\extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.


Or sometimes when I change my code line's order I receive something like that:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\Render\app.py", line 11, in <module>
    db = SQLAlchemy(app)
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\flask_sqlalchemy\extension.py", line 219, in __init__
    self.init_app(app)
  File "C:\Users\Admin\PycharmProjects\Render\venv\lib\site-packages\flask_sqlalchemy\extension.py", line 301, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.


There is my code, I decided to start from scratch but there is still the same problem:

from flask import Flask, render_template, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

app = Flask(__name__)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
db = SQLAlchemy(app)
app.config['SECRET_KEY'] = 'thisissecretkey'


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(80), nullable=False)

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/login')
def login():
    return render_template('login.html')

@app.route('/register')
def register():
    return render_template('register.html')

if __name__ == '__main__':
    app.run(debug=True)


My app structer:

I hope someone will help me with this problem cuz I can't find solving already for 2 days...
I'm trying to import my database structure to my db file, tried change the order of initializing, saw many stack's posts but I didn't find solving

        